因为需要统计，group by ，所以，表定义修改如下。

CREATE TABLE `acquisition` (
  `READTIME` varchar(14) NOT NULL DEFAULT '20010203040506' COMMENT '采集时间',
  `YYYY`INT DEFAULT 2001 COMMENT 'YYYY',
  `MM` INT DEFAULT 2001 COMMENT 'MM FOR REPORT GROUP',
  `DD` INT DEFAULT 1 COMMENT 'DD FOR REPORT GROUP',
  `HH` INT DEFAULT 0 COMMENT 'HH FOR REPORT GROUP',
  `MS` INT DEFAULT 0 COMMENT 'MS FOR REPORT GROUP',
  `SS` INT DEFAULT 0 COMMENT 'MM FOR REPORT GROUP',
  `TIMEINTERVAL` INT DEFAULT 0 COMMENT '采集间隔(秒)',

  `WINDDIRECT`  FLOAT DEFAULT 0 COMMENT '风向(度)',
  `WINDDIRECTFLG`  INT DEFAULT 0 COMMENT '风向(0：有效 1：无效)',

  `WINDSPEED`  FLOAT DEFAULT 0 COMMENT '风速(米/秒)',
  `WINDSPEEDFLG`  INT DEFAULT 0 COMMENT '风速(0：有效 1：无效)',

  `NOISE`  FLOAT DEFAULT 0 COMMENT '噪音(分贝)',
  `NOISEFLG`  INT DEFAULT 0 COMMENT '噪音(0：有效 1：无效)',

  `PRESSURE` FLOAT DEFAULT 0 COMMENT '大气压(帕)',
  `PRESSUREFLG` INT DEFAULT 0 COMMENT '大气压(0：有效 1：无效)',

  `TEMPERATURE` FLOAT DEFAULT 0 COMMENT '温度(摄氏度)',
  `TEMPERATUREFLG` INT DEFAULT 0 COMMENT '温度有效FLG(0：有效 1：无效)',

  `HUMIDITY`  FLOAT DEFAULT 0 COMMENT '湿度(百分比)',
  `HUMIDITYFLG`  INT DEFAULT 0 COMMENT '湿度(0：有效 1：无效)',

  `GRANDTEMPERATURE` FLOAT DEFAULT 0 COMMENT '地面温度(摄氏度)',
  `GRANDTEMPERATUREFLG` INT DEFAULT 0 COMMENT '地面温度有效FLG(0：有效 1：无效)',

  `GRANDHUMIDITY`  FLOAT DEFAULT 0 COMMENT '地面湿度(百分比)',
  `GRANDHUMIDITYFLG`  INT DEFAULT 0 COMMENT '地面湿度(0：有效 1：无效)',

  `GRIPLEVEL`  FLOAT DEFAULT 0 COMMENT '地面滑溜系列(百分比)',
  `GRIPLEVELFLG`  INT DEFAULT 0 COMMENT '地面滑溜系列(0：有效 1：无效)',

  `WATERPERCENT`  FLOAT DEFAULT 0 COMMENT '地面含水量(毫米)',
  `WATERPERCENTFLG`  INT DEFAULT 0 COMMENT '地面含水量(0：有效 1：无效)',
  PRIMARY KEY (`READTIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `acquisitionHISTORY` (
   `READTIME` varchar(14) NOT NULL DEFAULT '20010203040506' COMMENT '采集时间',
  `YYYY`INT DEFAULT 2001 COMMENT 'YYYY',
  `MM` INT DEFAULT 2001 COMMENT 'MM FOR REPORT GROUP',
  `DD` INT DEFAULT 1 COMMENT 'DD FOR REPORT GROUP',
  `HH` INT DEFAULT 0 COMMENT 'HH FOR REPORT GROUP',
  `MS` INT DEFAULT 0 COMMENT 'MS FOR REPORT GROUP',
  `SS` INT DEFAULT 0 COMMENT 'MM FOR REPORT GROUP',
  `TIMEINTERVAL` INT DEFAULT 0 COMMENT '采集间隔(秒)',

  `WINDDIRECT`  FLOAT DEFAULT 0 COMMENT '风向(度)',
  `WINDDIRECTFLG`  INT DEFAULT 0 COMMENT '风向(0：有效 1：无效)',

  `WINDSPEED`  FLOAT DEFAULT 0 COMMENT '风速(米/秒)',
  `WINDSPEEDFLG`  INT DEFAULT 0 COMMENT '风速(0：有效 1：无效)',

  `NOISE`  FLOAT DEFAULT 0 COMMENT '噪音(分贝)',
  `NOISEFLG`  INT DEFAULT 0 COMMENT '噪音(0：有效 1：无效)',

  `PRESSURE` FLOAT DEFAULT 0 COMMENT '大气压(帕)',
  `PRESSUREFLG` INT DEFAULT 0 COMMENT '大气压(0：有效 1：无效)',

  `TEMPERATURE` FLOAT DEFAULT 0 COMMENT '温度(摄氏度)',
  `TEMPERATUREFLG` INT DEFAULT 0 COMMENT '温度有效FLG(0：有效 1：无效)',

  `HUMIDITY`  FLOAT DEFAULT 0 COMMENT '湿度(百分比)',
  `HUMIDITYFLG`  INT DEFAULT 0 COMMENT '湿度(0：有效 1：无效)',

  `GRANDTEMPERATURE` FLOAT DEFAULT 0 COMMENT '地面温度(摄氏度)',
  `GRANDTEMPERATUREFLG` INT DEFAULT 0 COMMENT '地面温度有效FLG(0：有效 1：无效)',

  `GRANDHUMIDITY`  FLOAT DEFAULT 0 COMMENT '地面湿度(百分比)',
  `GRANDHUMIDITYFLG`  INT DEFAULT 0 COMMENT '地面湿度(0：有效 1：无效)',

  `GRIPLEVEL`  FLOAT DEFAULT 0 COMMENT '地面滑溜系列(百分比)',
  `GRIPLEVELFLG`  INT DEFAULT 0 COMMENT '地面滑溜系列(0：有效 1：无效)',

  `WATERPERCENT`  FLOAT DEFAULT 0 COMMENT '地面含水量(毫米)',
  `WATERPERCENTFLG`  INT DEFAULT 0 COMMENT '地面含水量(0：有效 1：无效)',
  PRIMARY KEY (`READTIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
